INSERT INTO Faculty VALUES (2 , "Magdy", "Ellabidy", 2, "Dobbs", 139, 3.9);
INSERT INTO Faculty VALUES (3, "Karina", "Assiter", 2, "Dobbs", 141, 1.9);
INSERT INTO Faculty VALUES (4’, "Nate", "Derbinsky", 2, "Dobbs", 144, 5);
INSERT INTO Faculty VALUES (5, "Jones", "Yu", 2, "Dobbs", 135, 4.8);
INSERT INTO Faculty VALUES (6, "Francis", "Hopcroft", 3, "Annex Central", 308, 3.3);
INSERT INTO Faculty VALUES (7, "Vitaliy", "Saykin", 3, "Annex South", 101, 2.7);
INSERT INTO Faculty VALUES (8, "Joseph", "Martel-Foley", 4, "Ira Allen", 310, 3.9);
INSERT INTO Faculty VALUES (9, "Ali", "Moazed", 4, "Kingman", 206, 3.5);
INSERT INTO Faculty VALUES (10, "Douglas", "Sondak", 4, "Kingman", 210, NULL);
INSERT INTO Faculty VALUES (11,"Song","Jenny",5,"Dobs",220,4.8);
INSERT INTO Faculty VALUES (12,"Carpenter","Aaron",5,"Dobs",206,5.0);
INSERT INTO Faculty VALUES (13,"Yang-Keathly","Yugu",5,"Dobs",210,2.4);
INSERT INTO Faculty VALUES (14,"Douglas","Dow",5,"Ira Allen",114,3.5);
INSERT INTO Faculty VALUES (15,"Khabari","Ali",5,"Dobs",205,4.3);
INSERT INTO Faculty VALUES (16,"Birkett","David",5,"Dobs",NULL,2.4);
INSERT INTO Faculty VALUES (17,"Bynoe","Wayne",5,"Dobs",216,1.0);
INSERT INTO Faculty VALUES (18,"Dasgupta","Siben",5,"Dobs",208,3.6);
INSERT INTO Faculty VALUES (19,"Grenquist","Scott",5,"Dobs",207,4.6);
INSERT INTO Faculty VALUES (20,"Majidi","Rabeeh",5,"Dobs",220,3.8);
INSERT INTO Faculty VALUES (21,"McCusker","James",5,"Dobs",209,4.3);
INSERT INTO Faculty VALUES (22,"Santacroce","Joseph",5,"Dobs",218,4.0);
INSERT INTO Faculty VALUES (26,"Leonard","Anderson",3,"Annex South",101,1.6);
INSERT INTO Faculty VALUES (27,"Tugba","Arsava",3,"Annex Central",304,NULL);
INSERT INTO Faculty VALUES (28,"Abigail","Charest",3,NULL,NULL,2.1);
INSERT INTO Faculty VALUES (29,"Gautham","Das",3,"Annex Central",312,4.0);
INSERT INTO Faculty VALUES (30,"Michael","Davidson",3,"Annex South",101,4.3);
INSERT INTO Faculty VALUES (31,"Jerry","Hopcroft",3,"Annex South",101,NULL);
INSERT INTO Faculty VALUES (32,"Anuja","Kama",3,"Annex Central",304,1.5);
INSERT INTO Faculty VALUES (33,"Jim","Lambrechts",3,"Annex South",101,NULL);
INSERT INTO Faculty VALUES (34,"Henderson","Pritchard",3,"Annex Central",309,3.4);
