CREATE TABLE "Software" (
	`SoftwareID`	INTEGER,
	`URL`	TEXT UNIQUE,
	`Name`	TEXT,
	`ClassID`	TEXT,
	PRIMARY KEY(`SoftwareID`),
	FOREIGN KEY(`ClassID`) REFERENCES Class(ClassID)
);

INSERT INTO Software VALUES (1, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf","Adobe Reader DC", "COMP-1000");
INSERT INTO Software VALUES (2, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf","Adobe Reader DC", "COMP-1100");
INSERT INTO Software VALUES (3, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf","Adobe Reader DC", "COMP-2500");
INSERT INTO Software VALUES (4, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf","Adobe Reader DC", "COMP-2000");
INSERT INTO Software VALUES (5, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf","Adobe Reader DC", "COMP-3071");
INSERT INTO Software VALUES (6, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf","Adobe Reader DC", "COMP-3071");
INSERT INTO Software VALUES (9, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Apache Tomcat", "COMP-1000");
INSERT INTO Software VALUES (10, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Apache Tomcat", "COMP-1100");
INSERT INTO Software VALUES (11, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Apache Tomcat", "COMP-2500");
INSERT INTO Software VALUES (12, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Apache Tomcat", "COMP-2000");
INSERT INTO Software VALUES (13, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Apache Tomcat", "COMP-3071");
INSERT INTO Software VALUES (16, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Bonjour", "COMP-1000");
INSERT INTO Software VALUES (17, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Bonjour", "COMP-1100");
INSERT INTO Software VALUES (18, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Bonjour", "COMP-2500");
INSERT INTO Software VALUES (19, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Bonjour", "COMP-2000");
INSERT INTO Software VALUES (20, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Bonjour", "COMP-3071");
INSERT INTO Software VALUES (23, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "TASM", "COMP-1000");
INSERT INTO Software VALUES (24, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "TASM", "COMP-1100");
INSERT INTO Software VALUES (25, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "TASM", "COMP-2500");
INSERT INTO Software VALUES (26, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "TASM", "COMP-2000");
INSERT INTO Software VALUES (27, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "TASM", "COMP-3071");
INSERT INTO Software VALUES (28, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Eclipse", "COMP-1000");
INSERT INTO Software VALUES (29, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Eclipse", "COMP-1100");
INSERT INTO Software VALUES (30, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Eclipse", "COMP-2500");
INSERT INTO Software VALUES (31, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Eclipse", "COMP-2000");
INSERT INTO Software VALUES (32, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Eclipse", "COMP-3071");
INSERT INTO Software VALUES (33, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Kexi FileMaker Pro", "COMP-1000");
INSERT INTO Software VALUES (34, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Kexi FileMaker Pro", "COMP-1100");
INSERT INTO Software VALUES (35, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Kexi FileMaker Pro", "COMP-2500");
INSERT INTO Software VALUES (36, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Kexi FileMaker Pro", "COMP-2000");
INSERT INTO Software VALUES (37, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Kexi FileMaker Pro", "COMP-3071");
INSERT INTO Software VALUES (38, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "MATLAB", "COMP-1000");
INSERT INTO Software VALUES (39, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "MATLAB", "COMP-1100");
INSERT INTO Software VALUES (40, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "MATLAB", "COMP-2500");
INSERT INTO Software VALUES (41, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "MATLAB", "COMP-2000");
INSERT INTO Software VALUES (42, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "MATLAB", "COMP-3071");
INSERT INTO Software VALUES (43, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Symbolic Math Tool Box", "COMP-1000");
INSERT INTO Software VALUES (44, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Symbolic Math Tool Box", "COMP-1100");
INSERT INTO Software VALUES (45, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Symbolic Math Tool Box", "COMP-2500");
INSERT INTO Software VALUES (46, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Symbolic Math Tool Box", "COMP-2000");
INSERT INTO Software VALUES (47, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Symbolic Math Tool Box", "COMP-3071");
INSERT INTO Software VALUES (48, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Database Tool Box", "COMP-1000");
INSERT INTO Software VALUES (49, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Database Tool Box", "COMP-1100");
INSERT INTO Software VALUES (50, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Database Tool Box", "COMP-2500");
INSERT INTO Software VALUES (51, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Database Tool Box", "COMP-2000");
INSERT INTO Software VALUES (52, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Database Tool Box", "COMP-3071");
INSERT INTO Software VALUES (53, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Computational Biology", "COMP-1000");
INSERT INTO Software VALUES (54, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Computational Biology", "COMP-1100");
INSERT INTO Software VALUES (55, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Computational Biology", "COMP-2500");
INSERT INTO Software VALUES (56, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Computational Biology", "COMP-2000");
INSERT INTO Software VALUES (57, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Computational Biology", "COMP-3071");
INSERT INTO Software VALUES (58, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Bioinformatics Tool Box", "COMP-1000");
INSERT INTO Software VALUES (59, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Bioinformatics Tool Box", "COMP-1100");
INSERT INTO Software VALUES (60, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Bioinformatics Tool Box", "COMP-2500");
INSERT INTO Software VALUES (61, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Bioinformatics Tool Box", "COMP-2000");
INSERT INTO Software VALUES (62, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Bioinformatics Tool Box", "COMP-3071");
INSERT INTO Software VALUES (63, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Sim-Biology", "COMP-1000");
INSERT INTO Software VALUES (64, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Sim-Biology", "COMP-1100");
INSERT INTO Software VALUES (65, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Sim-Biology", "COMP-2500");
INSERT INTO Software VALUES (66, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Sim-Biology", "COMP-2000");
INSERT INTO Software VALUES (67, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Sim-Biology", "COMP-3071");
INSERT INTO Software VALUES (68, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "CutePDF", "COMP-1000");
INSERT INTO Software VALUES (69, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "CutePDF", "COMP-1100");
INSERT INTO Software VALUES (70, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "CutePDF", "COMP-2500");
INSERT INTO Software VALUES (71, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "CutePDF", "COMP-2000");
INSERT INTO Software VALUES (72, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "CutePDF", "COMP-3071");
INSERT INTO Software VALUES (73, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Java DB", "COMP-1000");
INSERT INTO Software VALUES (74, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Java DB", "COMP-1100");
INSERT INTO Software VALUES (75, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Java DB", "COMP-2500");
INSERT INTO Software VALUES (76, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Java DB", "COMP-2000");
INSERT INTO Software VALUES (77, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Java DB", "COMP-3071");
INSERT INTO Software VALUES (78, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Java (TM)SE Development Kit", "COMP-1000");
INSERT INTO Software VALUES (79, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Java (TM)SE Development Kit", "COMP-1100");
INSERT INTO Software VALUES (80, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Java (TM)SE Development Kit", "COMP-2500");
INSERT INTO Software VALUES (81, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Java (TM)SE Development Kit", "COMP-2000");
INSERT INTO Software VALUES (82, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Java (TM)SE Development Kit", "COMP-3071");
INSERT INTO Software VALUES (83, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Java Runtime Environment", "COMP-1000");
INSERT INTO Software VALUES (84, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Java Runtime Environment", "COMP-1100");
INSERT INTO Software VALUES (85, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Java Runtime Environment", "COMP-2500");
INSERT INTO Software VALUES (86, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Java Runtime Environment", "COMP-2000");
INSERT INTO Software VALUES (87, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Java Runtime Environment", "COMP-3071");
INSERT INTO Software VALUES (88, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Java SDK", "COMP-1000");
INSERT INTO Software VALUES (89, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Java SDK", "COMP-1100");
INSERT INTO Software VALUES (90, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Java SDK", "COMP-2500");
INSERT INTO Software VALUES (92, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Java SDK", "COMP-2000");
INSERT INTO Software VALUES (93, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Java SDK", "COMP-3071");
INSERT INTO Software VALUES (94, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Java Production Kit", "COMP-1000");
INSERT INTO Software VALUES (95, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Java Production Kit", "COMP-1100");
INSERT INTO Software VALUES (96, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Java Production Kit", "COMP-2500");
INSERT INTO Software VALUES (97, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Java Production Kit", "COMP-2000");
INSERT INTO Software VALUES (98, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Java Production Kit", "COMP-3071");
INSERT INTO Software VALUES (99, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Windows Internet Explorer", "COMP-1000");
INSERT INTO Software VALUES (100, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Windows Internet Explorer", "COMP-1100");
INSERT INTO Software VALUES (101, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Windows Internet Explorer", "COMP-2500");
INSERT INTO Software VALUES (102, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Windows Internet Explorer", "COMP-2000");
INSERT INTO Software VALUES (103, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Windows Internet Explorer", "COMP-3071");
INSERT INTO Software VALUES (104, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Office Suite Professional", "COMP-1000");
INSERT INTO Software VALUES (105, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Office Suite Professional", "COMP-1100");
INSERT INTO Software VALUES (106, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Office Suite Professional", "COMP-2500");
INSERT INTO Software VALUES (107, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Office Suite Professional", "COMP-2000");
INSERT INTO Software VALUES (108, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Office Suite Professional", "COMP-3071");
INSERT INTO Software VALUES (109, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Office Project Professional", "COMP-1000");
INSERT INTO Software VALUES (110, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Office Project Professional", "COMP-1100");
INSERT INTO Software VALUES (111, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Office Project Professional", "COMP-2500");
INSERT INTO Software VALUES (112, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Office Project Professional", "COMP-2000");
INSERT INTO Software VALUES (113, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Office Project Professional", "COMP-3071");
INSERT INTO Software VALUES (114, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Office Publisher Professional", "COMP-1000");
INSERT INTO Software VALUES (115, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Office Publisher Professional", "COMP-1100");
INSERT INTO Software VALUES (116, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Office Publisher Professional", "COMP-2500");
INSERT INTO Software VALUES (117, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Office Publisher Professional", "COMP-2000");
INSERT INTO Software VALUES (118, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Office Publisher Professional", "COMP-3071");
INSERT INTO Software VALUES (119, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Office Visio Professional", "COMP-1000");
INSERT INTO Software VALUES (120, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Office Visio Professional", "COMP-1100");
INSERT INTO Software VALUES (121, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Office Visio Professional", "COMP-2500");
INSERT INTO Software VALUES (122, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Office Visio Professional", "COMP-2000");
INSERT INTO Software VALUES (123, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Office Visio Professional", "COMP-3071");
INSERT INTO Software VALUES (124, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Visual Studio Professional Edition", "COMP-1000");
INSERT INTO Software VALUES (125, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Visual Studio Professional Edition", "COMP-1100");
INSERT INTO Software VALUES (126, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Visual Studio Professional Edition", "COMP-2500");
INSERT INTO Software VALUES (127, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Visual Studio Professional Edition", "COMP-2000");
INSERT INTO Software VALUES (128, "https://www.wit.edu/sites/default/files/technology-services/pdfs/CSS-Software%202015.pdf" , "Visual Studio Professional Edition", "COMP-3071");
